apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: alpine_mysql
        imagePullPolicy: Never
        env:
        - name: WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_db_name
        - name: WP_USER
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_password
        livenessProbe:
         exec:
            command:
            - /bin/ash
            - /live/isalivesql.sh
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-volume
      volumes:
       - name: mysql-persistent-volume
         persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql