apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: alpine_phpmyadmin
        imagePullPolicy: Never
        env:
        - name: MYSQL_IP
          value: mysql-service
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /srcs/isalivephp.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.5
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: phpmyadmin