apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: alpine_wordpress
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubernetes-secret
              key: wp_password
        - name: DB_HOST
          value: mysql-service
        livenessProbe:
          exec:
            command:
              - /bin/ash
              - /live/isalivewordpress.sh
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.4
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: wordpress